DROP DATABASE IF EXISTS moviesDB;
CREATE DATABASE moviesDB;
USE moviesDB;

CREATE TABLE films (
  id INTEGER NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  year VARCHAR (4) NOT NULL,
  genre VARCHAR (255) NOT NULL,
  price INTEGER NOT NULL,
  format VARCHAR (50) NULL,
  isReserved BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE Users (
 id INTEGER NOT NULL auto_increment,
 email VARCHAR(255) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 createdAt DATETIME NOT NULL,
 updatedAt DATETIME NOT NULL,
 PRIMARY KEY (id)
);



SELECT * FROM films;
