DROP DATABASE IF EXISTS moviesDB;
CREATE DATABASE moviesDB;
USE moviesDB;

CREATE TABLE films (
  id INTEGER NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  year VARCHAR (4) NOT NULL,
  genre VARCHAR (255) NOT NULL,
  price INTEGER NOT NULL,
  format VARCHAR (50) NULL,
  reserved BOOLEAN,
  PRIMARY KEY (id)
);


SELECT * FROM films;