DROP DATABASE IF EXISTS moviesDB;
CREATE DATABASE moviesDB;
USE DATABASE moviesDB;

CREATE TABLE films (
  id INTEGER NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  year VARCHAR NOT NULL,
  genre VARCHAR (255) NOT NULL
  price INTEGER NOT NULL,
  format VARCHAR (50) NULL,
  PRIMARY KEY (id)
);

INSERT INTO films (title, year, genre, price, format)
VALUES ("20,000 Leagues Under the Sea", "1954", "Adventure Drama Family", 2.99, "VHS");
VALUES ("2001: A Space Odyssey", "1968", "Adventure Sci-Fi", 2.99, "VHS");
VALUES ("A Bronx Tale", "1993", "Crime Drama Romance", 2.99, "VHS");
VALUES ("A Christmas Story", "1983", "Comedy Family", 2.99, "VHS");
VALUES ("A Clockwork Orange", "1971", "Crime Drama Sci-Fi", 2.99, "VHS");
VALUES ("A Few Good Men", "1992", "Drama Thriller", 2.99, "VHS");
VALUES ("A Fish Called Wanda", "1988", "Comedy Crime", 2.99, "VHS");
VALUES ("A League of Their Own", "1992", "Comedy Drama Family", 2.99, "VHS");
VALUES ("A Nightmare on Elm Street", "1984", "Horror", 2.99, "VHS");
VALUES ("A River Runs Through It", "1992", "Drama", 2.99, "VHS");
VALUES ("Ace Ventura: Pet Detective", "1994", "Comedy", 2.99, "VHS");
VALUES ("Advenures in Babysitting", "1987", "Adventure Comedy Crime", 2.99, "VHS");
VALUES ("Aguirre, The Wrath of God", "1972", "Adventure Biography Drama", 2.99, "VHS");
VALUES ("Airplane", "1980", "Comedy", 2.99, "VHS");
VALUES ("Airport", "1970", "Action Drama Thriller", 2.99, "VHS");
VALUES ("Akira", "1988", "Animation Drama Sci-Fi", 2.99, "VHS");
VALUES ("Aladdin", "1992", "Animation Adventure Comedy", 2.99, "VHS");
VALUES ("Alien", "1979", "Horror Sci-Fi", 2.99, "VHS");
VALUES ("Alien 3", "1992", "Action Horror Sci-Fi", 2.99, "VHS");
VALUES ("Aliens", "1986", "Action Adventure Sci-Fi", 2.99, "VHS");
VALUES ("All Quiet on the Western Front", "1930", "Drama War History", 2.99, "VHS");
VALUES ("All the President's Men", "1976", "Biography Drama History", 2.99, "VHS");
VALUES ("Amadeus", "1984", "Biography Drama History", 2.99, "VHS");
VALUES ("American Graffiti", "1973", "Comedy, Drama", 2.99, "VHS");
VALUES ("Army of Darkness", "1992", "Comedy Horror", 2.99, "VHS");
VALUES ("Assault on Precinct 13", "1976", "Action Crime Thriller", 2.99, "VHS");
VALUES ("Back to the Future", "1985", "Adventure Comedy Sci-Fi", 2.99, "VHS");
VALUES ("Back to the Future Part II", "1989", "Adventure Comedy Sci-Fi", 2.99, "VHS");
VALUES ("Back to the Future Part III", "1990", "Adventure Comedy Sci-Fi", 2.99, "VHS");
VALUES ("Badlands", "1973", "Crime Drama", 2.99, "VHS");
VALUES ("Bambi", "1942", "Animation Drama Family", 2.99, "VHS");
VALUES ("Barton Fink", "1991", "Comedy Drama Thriller", 2.99, "VHS");
VALUES ("Basic Instinct", "1992", "Drama Mystery Thriller", 2.99, "VHS");
VALUES ("Batman", "1989", "Action Crime Superhero", 2.99, "VHS");
VALUES ("Batman Returns", "1992", "Action Crime Superhero", 2.99, "VHS");
VALUES ("Beauty and the Beast", "1991", "Animation Family Fantasy", 2.99, "VHS");
VALUES ("Beetlejuice", "1988", "Comedy Fantasy", 2.99, "VHS");
VALUES ("Before Sunrise", "1995", "Drama Romance", 2.99, "VHS");
VALUES ("Ben-Hur", "1959", "Adventure Drama History", 2.99, "VHS");
VALUES ("Better Off Dead", "1985", "Comedy Romance", 2.99, "VHS");
VALUES ("Beverly Hills Cop", "1984", "Action Comedy Crime", 2.99, "VHS");
VALUES ("Big", "1988", "Comedy Drama Family", 2.99, "VHS");
VALUES ("Big Trouble in Little China", "1986", "Action Adventure Comedy", 2.99, "VHS");
VALUES ("Bill & Ted's Excellent Adventure", "1989", "Adventure Comedy Music", 2.99, "VHS");
VALUES ("Blade Runner", "1982", "Sci-Fi Thriller", 2.99, "VHS");
VALUES ("Blazing Saddles", "1974", "Comedy Western", 2.99, "VHS");
VALUES ("Blue Velvet", "1986", "Drama Mystery Thriller", 2.99, "VHS");
VALUES ("Born on the Fourth of July", "1989", "Biography Drama War", 2.99, "VHS");
VALUES ("Bram Stoker's Dracula", "1992", "Horror", 2.99, "VHS");
VALUES ("Braveheart", "1995", "Biography Drama History", 2.99, "VHS");
VALUES ("Broadcast News", "1987", "Comedy Drama Romance", 2.99, "VHS");
VALUES ("Butch Cassidy and the Sundance Kid", "1969", "Biography Crime Drama", 2.99, "VHS");
VALUES ("Cabaret", "1972", "Drama Musical", 2.99, "VHS");
VALUES ("Caddyshack", "1980", "Comedy Sport", 2.99, "VHS");
VALUES ("Cape Fear", "1991", "Crime Thriller", 2.99, "VHS");
VALUES ("Carrie", "1976", "Horror", 2.99, "VHS");
VALUES ("Casino", "1995", "Crime Drama", 2.99, "VHS");
VALUES ("Chinatown", "1974", "Drama Mystery Thriller", 2.99, "VHS");
VALUES ("Cinderella", "1950", "Animation Family Fantasy", 2.99, "VHS");
VALUES ("Cleopatra", "1963", "Biography Drama History", 2.99, "VHS");
VALUES ("Clerks", "1994", "Comedy", 2.99, "VHS");
VALUES ("Close Encounters of the Third Kind", "1977", "Drama Sci-Fi", 2.99, "VHS");
VALUES ("Coming to America", "1988", "Comedy Romance", 2.99, "VHS");
VALUES ("Commando", "1985", "Action Adventure Thriller", 2.99, "VHS");
VALUES ("D2: The Mighty Ducks", "1994", "Comedy Drama Family", 2.99, "VHS");
VALUES ("Dances with Wolves", "1990", "Adventure Drama Western", 2.99, "VHS");
VALUES ("Dawn of the Dead", "1979", "Horror Thriller", 2.99, "VHS");
VALUES ("Days of Heaven", "1978", "Drama Romance", 2.99, "VHS");
VALUES ("Dead Poets Society", "1989", "Comedy Drama", 2.99, "VHS");
VALUES ("Delicatessen", "1991", "Comedy Crime", 2.99, "VHS");
VALUES ("Deliverance", "1972", "Adventure Drama Thriller", 2.99, "VHS");
VALUES ("Demolition Man", "1993", "Action Crime Sci-Fi", 2.99, "VHS");
VALUES ("Desperataly Seeking Susan", "1985", "Comedy Drama", 2.99, "VHS");
VALUES ("Diamonds Are Forever", "1971", "Action Adventure Thriller", 2.99, "VHS");
VALUES ("Die Hard", "1988", "Action Thriller Holiday", 2.99, "VHS");
VALUES ("Die Hard with a Vengeance", "1995", "Action Adventure Thriller", 2.99, "VHS");
VALUES ("Dirty Dancing", "1987", "Drama Music Romance", 2.99, "VHS");
VALUES ("Dirty Harry", "1971", "Action Crime Thriller", 2.99, "VHS");
VALUES ("Disclosure", "1994", "Drama Thriller", 2.99, "VHS");
VALUES ("Do the Right Thing", "1989", "Comedy Drama", 2.99, "VHS");
VALUES ("Dog Day Afternoon", "1975", "Biography Crime Drama", 2.99, "VHS");
VALUES ("Driving Miss Daisy", "1989", "Drama", 2.99, "VHS");
VALUES ("Drunken Master", "1978", "Action Comedy", 2.99, "VHS");
VALUES ("Drunken Master II", "1994", "Action Comedy", 2.99, "VHS");
VALUES ("Dumb and Dumber", "1994", "Comedy", 2.99, "VHS");
VALUES ("E.T. the Extra-Terrestrial", "1982", "Family Sci-Fi", 2.99, "VHS");
VALUES ("Ed Wood", "1994", "Biography Comedy Drama", 2.99, "VHS");
VALUES ("Edward Scissorhands", "1990", "Drama Family Romance", 2.99, "VHS");
VALUES ("Enter the Dragon", "1973", "Action Crime, Drama", 2.99, "VHS");
VALUES ("Eraserhead", "1977", "Horror", 2.99, "VHS");
VALUES ("Escape From New York", "1981", "Action Adventure Sci-Fi", 2.99, "VHS");
VALUES ("Evid Dead 2: Dead by Dawn", "1987", "Comedy Horror", 2.99, "VHS");
VALUES ("Falling Down", "1993", "Crime Drama Thriller", 2.99, "VHS");
VALUES ("Fast Times at Ridgemont High", "1982", "Comedy Drama", 2.99, "VHS");
VALUES ("Fatal Attraction", "1987", "Drama Thriller", 2.99, "VHS");
VALUES ("Fearless", "1993", "Drama Thriller", 2.99, "VHS");
VALUES ("Ferris Bueller's Day Off", "1986", "Comedy", 2.99, "VHS");
VALUES ("Fiddler on the Roof", "1971", "Drama Family Musical", 2.99, "VHS");
VALUES ("Field of Dreams", "1989", "Drama Family Fantasy", 2.99, "VHS");
VALUES ("Flashdance", "1983", "Drama Music Romance", 2.99, "VHS");
VALUES ("Footloose", "1984", "Drama Music Romance", 2.99, "VHS");
VALUES ("For Whom the Bell Tolls", "1943", "Adventure Drama History", 2.99, "VHS");
VALUES ("Forrest Gump", "1994", "Drama Romance", 2.99, "VHS");
VALUES ("Four Weddings and a Funeral", "1994", "Comedy Drama Romance", 2.99, "VHS");
VALUES ("Frankenstein", "1931", "Drama Horror Sci-fi", 2.99, "VHS");
VALUES ("Friday the 13th", "1980", "Horror", 2.99, "VHS");
VALUES ("From Russia with Love", "1963", "Action Adventure Thriller", 2.99, "VHS");
VALUES ("Full Metal Jacket", "1987", "Comedy War Drama", 2.99, "VHS");
VALUES ("Funny Girl", "1968", "Biography Comedy Drama", 2.99, "VHS");
VALUES ("Ghost", "1990", "Drama Romance", 2.99, "VHS");
VALUES ("Ghostbusters", "1984", "Action Comedy Sci-Fi", 2.99, "VHS");
VALUES ("Ghostbusters II", "1989", "Action Comedy Sci-Fi", 2.99, "VHS");
VALUES ("Glengarry Glen Ross", "1992", "Drama", 2.99, "VHS");
VALUES ("Glory", "1989", "Drama War History", 2.99, "VHS");
VALUES ("Goldfinger", "1964", "Action Adventure Thriller", 2.99, "VHS");
VALUES ("Goodfellsa", "1990", "Crime Action Drama", 2.99, "VHS");
VALUES ("Grave of the Fireflies", "1988", "Animation Drama War", 2.99, "VHS");
VALUES ("Grease", "1978", "Musical Romance", 2.99, "VHS");
VALUES ("Gremlins", "1984", "Action Sci-Fi Comedy", 2.99, "VHS");
VALUES ("Grey Gardens", "1975", "Documentary Comedy Drama", 2.99, "VHS");
VALUES ("Groundhog Day", "1993", "Comedy", 2.99, "VHS");
VALUES ("Grumpy Old Men", "1993", "Drama", 2.99, "VHS");
VALUES ("Halloween", "1978", "Horror Thriller", 2.99, "VHS");
VALUES ("Hawaii", "1966", "Drama", 2.99, "VHS");
VALUES ("Heat", "1995", "Crime Drama Thriller", 2.99, "VHS");
VALUES ("Heathers", "1988", "Comedy Drama Action", 2.99, "VHS");
VALUES ("Highlander", "1986", "Action Adventure Fantasy", 2.99, "VHS");
VALUES ("Home Alone 2: Lost in New York", "1992", "Family Drama Holiday", 2.99, "VHS");
VALUES ("Hook", "1991", "Fantasy Family Drama", 2.99, "VHS");
VALUES ("House", "1977", "Comedy Horror Japanese", 2.99, "VHS");
VALUES ("In the Name of the Father", "1993", "Biography Drama", 2.99, "VHS");
VALUES ("Indiana Jones and the Last Crusade", "1989", "Adventure Action Comedy", 2.99, "VHS");
VALUES ("Indiana Jones and the Temple of Doom", "1984", "Adventure Action Comedy", 2.99, "VHS");
VALUES ("Indiana Jones Raiders of the Lost Ark", "1981", "Action Adventure", 2.99, "VHS");
VALUES ("Interview with the Vampire", "1994", "Drama Horro", 2.99, "VHS");
VALUES ("Invasion of the Body Snatchers", "1978", "Horror Sci-Fi", 2.99, "VHS");
VALUES ("Jaws", "1975", "Adventure Drama Thriller", 2.99, "VHS");
VALUES ("JFK", "1991", "Biography Drama History", 2.99, "VHS");
VALUES ("Jurassic Park", "1993", "Action Adventure Sci-Fi", 2.99, "VHS");
VALUES ("Karate Kid", "1984", "Action Drama Family", 2.99, "VHS");
VALUES ("Kramer VS. Kramer", "1979", "Drama", 2.99, "VHS");
VALUES ("Labyrinth", "1986", "Adventure Family Fantasy", 2.99, "VHS");
VALUES ("Lady and the Tramp", "1955", "Animation Adventure Comedy", 2.99, "VHS");
VALUES ("Ladybugs", "1992", "Comedy Sport", 2.99, "VHS");
VALUES ("Last Action Hero", "1993", "Action Adventure Comedy", 2.99, "VHS");
VALUES ("Lawrence of Arabia", "1962", "Adventure Biography Drama", 2.99, "VHS");
VALUES ("Léon: The Professional", "1994", "Action Crime Drama", 2.99, "VHS");
VALUES ("Lethal Weapon", "1987", "Action Comedy Crime", 2.99, "VHS");
VALUES ("Little Shop of Horrors", "1986", "Comedy Horror Musical", 2.99, "VHS");
VALUES ("Little Women", "1994", "Drama Family Romance", 2.99, "VHS");
VALUES ("Loaded Weapon", "1993", "Action Comedy Crime", 2.99, "VHS");
VALUES ("Lost in America", "1985", "Comedy", 2.99, "VHS");
VALUES ("Love Story", "1970", "Drama Romance", 2.99, "VHS");
VALUES ("M*A*S*H", "1970", "Comedy Drama War", 2.99, "VHS");
VALUES ("Mad Max 2: The Road Warrior", "1982", "Action Adventure Sci-Fi", 2.99, "VHS");
VALUES ("Malcolm X", "1992", "Biography Drama History", 2.99, "VHS");
VALUES ("Mary Shelley's Frankenstein", "1994", "Drama Horro Romance", 2.99, "VHS");
VALUES ("Maverick", "1994", "Action Adventure Comedy", 2.99, "VHS");
VALUES ("Miracle on 34th Street", "1994", "Comedy Drama Family", 2.99, "VHS");
VALUES ("Monty Python and the Holy Grail", "1975", "Adventure Comedy Fantasy", 2.99, "VHS");
VALUES ("Monty Python's Life of Brian", "1979", "Comedy Drama Family", 2.99, "VHS");
VALUES ("Moonraker", "1979", "Action Adventure Sci-Fi", 2.99, "VHS");
VALUES ("Mrs. Miniver", "1942", "Drama Romance War", 2.99, "VHS");
VALUES ("My Cousin Vinny", "1992", "Comedy Crime", 2.99, "VHS");
VALUES ("My Fair Lady", "1964", "Drama Family Musical", 2.99, "VHS");
VALUES ("My Neighbor Totoro", "1988", "Animation Family Fantasy", 2.99, "VHS");
VALUES ("My Own Private Idaho", "1991", "Drama", 2.99, "VHS");
VALUES ("Mystic Pizza", "1988", "Comedy Drama Romance", 2.99, "VHS");
VALUES ("Naked Lunch", "1991", "Drama", 2.99, "VHS");
VALUES ("Nashville", "1975", "Comedy Drama Music", 2.99, "VHS");
VALUES ("National Lampoon's Animal House", "1978", "Comedy", 2.99, "VHS");
VALUES ("National Lampoon's Christmas Vacation", "1989", "Comedy", 2.99, "VHS");
VALUES ("National Lampoon's Vacation", "1983", "Adventure Comedy", 2.99, "VHS");
VALUES ("Natural Born Killers", "1994", "Crime Drama", 2.99, "VHS");
VALUES ("Network", "1976", "Drama", 2.99, "VHS");
VALUES ("Newsies", "1992", "Drama Family History", 2.99, "VHS");
VALUES ("Night on Earth", "1991", "Comedy Drama", 2.99, "VHS");
VALUES ("Of Mice and Men", "1992", "Drama", 2.99, "VHS");
VALUES ("One Hundred and One Dalmatians", "1961", "Animation Adventure Comedy", 2.99, "VHS");
VALUES ("Patriot Games", "1992", "Action Thriller", 2.99, "VHS");
VALUES ("Patton", "1970", "Biography Drama War", 2.99, "VHS");
VALUES ("Peter Pan", "1953", "Animation Adventure Family", 2.99, "VHS");
VALUES ("Philadelphia", "1993", "Drama", 2.99, "VHS");
VALUES ("Pink Flamingos", "1972", "Comedy Crime", 2.99, "VHS");
VALUES ("Pinocchio", "1940", "Animation Comedy Family", 2.99, "VHS");
VALUES ("Planes, Trains and Automobiles", "1987", "Comedy Holiday", 2.99, "VHS");
VALUES ("Platoon", "1986", "Drama War", 2.99, "VHS");
VALUES ("Point Break", "1991", "Action Crime Thriller", 2.99, "VHS");
VALUES ("Poltergeist", "1982", "Horror Thriller", 2.99, "VHS");
VALUES ("Predator", "1987", "Action Adventure Sci-Fi", 2.99, "VHS");
VALUES ("Pretty in Pink", "1986", "Comedy Drama Romance", 2.99, "VHS");
VALUES ("Psycho", "1960", "Horror Mystery Thriller", 2.99, "VHS");
VALUES ("Pulp Fiction", "1994", "Crime Drama", 2.99, "VHS");
VALUES ("Purple Rain", "1984", "Drama Music Musical", 2.99, "VHS");
VALUES ("Quiz Show", "1994", "Biography Drama History", 2.99, "VHS");
VALUES ("Raging Bull", "1980", "Biography Drama Sport", 2.99, "VHS");
VALUES ("Rain Man", "1988", "Drama", 2.99, "VHS");
VALUES ("Raising Arizona", "1987", "Comedy Crime", 2.99, "VHS");
VALUES ("Real Genius", "1985", "Comedy Romance Sci-Fi", 2.99, "VHS");
VALUES ("Reality Bites", "1994", "Comedy Drama Romance", 2.99, "VHS");
VALUES ("Rear Window", "1954", "Mystery Thriller", 2.99, "VHS");
VALUES ("Repo Man", "1984", "Comedy Crime Sci-Fi", 2.99, "VHS");
VALUES ("Reservoir Dogs", "1992", "Crime Drama Thriller", 2.99, "VHS");
VALUES ("Return to Oz", "1985", "Adventure Family Fantasy", 2.99, "VHS");
VALUES ("Revenge of the Nerds", "1984", "Comedy", 2.99, "VHS");
VALUES ("Risky Business", "1983", "Comedy Crime Drama", 2.99, "VHS");
VALUES ("Robin Hood", "1922", "Adventure Family Romance", 2.99, "VHS");
VALUES ("Robin Hood: Prince of Thieves", "1991", "Action Adventure Drama", 2.99, "VHS");
VALUES ("Robocop", "1987", "Action Crime Sci-Fi", 2.99, "VHS");
VALUES ("Rocky", "1976", "Drama Sport", 2.99, "VHS");
VALUES ("Rocky II", "1979", "Drama Sport", 2.99, "VHS");
VALUES ("Saturday Night Fever", "1977", "Drama Music", 2.99, "VHS");
VALUES ("Scanners", "1981", "Horror Sci-Fi Thriller", 2.99, "VHS");
VALUES ("Schindler's List", "1993", "Biography Drama History", 2.99, "VHS");
VALUES ("Se7en", "1995", "Crime Drama Mystery", 2.99, "VHS");
VALUES ("Serpico", "1973", "Biography Crime Drama", 2.99, "VHS");
VALUES ("Shaft", "1971", "Action Crime Thriller", 2.99, "VHS");
VALUES ("Shallow Grave", "1994", "Crime Thriller", 2.99, "VHS");
VALUES ("Short Circuit", "1986", "Comedy Family Sci-Fi", 2.99, "VHS");
VALUES ("Sister Act", "1992", "Comedy Crime Family", 2.99, "VHS");
VALUES ("Sixteen Candles", "1984", "Comedy Romance", 2.99, "VHS");
VALUES ("Slap Shot", "1977", "Comedy Drama Sport", 2.99, "VHS");
VALUES ("Sleepless in Seattle", "1993", "Comedy Drama Romance", 2.99, "VHS");
VALUES ("Smokey and the Bandit", "1977", "Action Comedy", 2.99, "VHS");
VALUES ("Solaris", "1976", "Drama Mystery Sci-Fi", 2.99, "VHS");
VALUES ("South Pacific", "1958", "Musical Romance War", 2.99, "VHS");
VALUES ("Soylent Green", "1973", "Crime Mystery Sci-FI", 2.99, "VHS");
VALUES ("Spaceballs", "1987", "Adventure Comedy Sci-Fi", 2.99, "VHS");
VALUES ("Spartacus", "1960", "Adventure Biography Drama", 2.99, "VHS");
VALUES ("Speed", "1994", "Action Adventure Crime", 2.99, "VHS");
VALUES ("St. Elmo's Fire", "1985", "Drama Romance", 2.99, "VHS");
VALUES ("Stand By Me", "1986", "Adventure Drama", 2.99, "VHS");
VALUES ("Star Wars", "1977", "Action Adventure Sci-Fi", 2.99, "VHS");
VALUES ("Star Wars Episode The Empire Strikes Back", "1980", "Action Adventure Sci-Fi", 2.99, "VHS");
VALUES ("Star Wars Episode Return of the Jedi", "1983", "Action Adventure Fantasy", 2.99, "VHS");
VALUES ("Stargate", "1994", "Action Adventure Sci-Fi", 2.99, "VHS");
VALUES ("Steel Magnolias", "1989", "Comedy Drama Romance", 2.99, "VHS");
VALUES ("Street Fighter", "1994", "Action Adventure Comedy", 2.99, "VHS");
VALUES ("Stripes", "1981", "Comedy War", 2.99, "VHS");
VALUES ("Superman", "1978", "Action Adventure Superhero", 2.99, "VHS");
VALUES ("Suspiria", "1977", "Horror", 2.99, "VHS");
VALUES ("Swimming With Sharks", "1994", "Comedy Crime", 2.99, "VHS");
VALUES ("Terminator 2: Judgment Day", "1991", "Action Sci-Fi", 2.99, "VHS");
VALUES ("Terms of Endearment", "1983", "Comedy Drama", 2.99, "VHS");
VALUES ("The Addams Family", "1991", "Comedy Fantasy", 2.99, "VHS");
VALUES ("The Bad News Bears", "1976", "Comedy Drama Family", 2.99, "VHS");
VALUES ("The Blues Brothers", "1980", "Adventure Crime Comedy", 2.99, "VHS");
VALUES ("The Breakfast Club", "1985", "Comedy Drama", 2.99, "VHS");
VALUES ("The Bridge on the River Kwai", "1957", "Adventure Drama War", 2.99, "VHS");
VALUES ("The Color Purple", "1985", "Drama", 2.99, "VHS");
VALUES ("The Crow", "1994", "Action Drama Fantasy", 2.99, "VHS");
VALUES ("The Deer Hunter", "1978", "Drama War", 2.99, "VHS");
VALUES ("The Doors", "1991", "Biography Drama Music", 2.99, "VHS");
VALUES ("The Exorcist", "1973", "Horror", 2.99, "VHS");
VALUES ("The Fisher King", "1991", "Comedy Drama Fantasy", 2.99, "VHS");
VALUES ("The Flintstones", "1994", "Comedy Family Fantasy", 2.99, "VHS");
VALUES ("The French Connection", "1971", "Action Crime Drama", 2.99, "VHS");
VALUES ("The Fugitive", "1993", "Action Crime Drama", 2.99, "VHS");
VALUES ("The Godfather", "1972", "Crime Drama", 2.99, "VHS");
VALUES ("The Godfather, Part II", "1974", "Crime Drama", 2.99, "VHS");
VALUES ("The Goonies", "1985", "Adventure Comedy Family", 2.99, "VHS");
VALUES ("The Graduate", "1967", "Comedy Drama Romance", 2.99, "VHS");
VALUES ("The Hand That Rocks the Cradle", "1992", "Drama Thriller", 2.99, "VHS");
VALUES ("The In-Laws", "1979", "Adventure Comedy Crime", 2.99, "VHS");
VALUES ("The Jerk", "1979", "Comedy", 2.99, "VHS");
VALUES ("The Jungle Book", "1967", "Animation Adventure Family", 2.99, "VHS");
VALUES ("The Jungle Book", "1994", "Adventure Family Romance", 2.99, "VHS");
VALUES ("The Land Before Time", "1988", "Action Adventure Sci-Fi", 2.99, "VHS");
VALUES ("The Last House on the Left", "1972", "Horror Thriller", 2.99, "VHS");
VALUES ("The Last of the Mohicans", "1992", "Action Adventure Drama", 2.99, "VHS");
VALUES ("The Last Starfighter", "1984", "Action Adventure Sci-Fi", 2.99, "VHS");
VALUES ("The Lion King", "1994", "Animation Adventure Drama", 2.99, "VHS");
VALUES ("The Little Mermaid", "1989", "Animation Family Fantasy", 2.99, "VHS");
VALUES ("The Little Rascals", "1994", "Comedy Family Romance", 2.99, "VHS");
VALUES ("The Longest Day", "1962", "Action Drama History", 2.99, "VHS");
VALUES ("The Lost Boys", "1987", "Comedy Horror", 2.99, "VHS");
VALUES ("The Man Who Fell to Earth", "1976", "Sci-Fi Drama", 2.99, "VHS");
VALUES ("The Mask", "1994", "Comedy Fantasy", 2.99, "VHS");
VALUES ("The Mighty Ducks", "1992", "Comedy Drama Family", 2.99, "VHS");
VALUES ("The Muppet Movie", "1979", "Adventure Comedy Family", 2.99, "VHS");
VALUES ("The Naked Gun: From the Files of Police Squad!", "1988", "Comedy Crime", 2.99, "VHS");
VALUES ("The NeverEnding Story", "1984", "Adventure Drama Family", 2.99, "VHS");
VALUES ("The NeverEnding Story II: The Next Chapter", "1990", "Adventure Drama Family", 2.99, "VHS");
VALUES ("The NeverEnding Story III", "1994", "Adventure Drama Family", 2.99, "VHS");
VALUES ("The Nightmare Before Christmas", "1993", "Animation Family Fantasy", 2.99, "VHS");
VALUES ("The Pagemaster", "1994", "Animation Adventure Comedy", 2.99, "VHS");
VALUES ("The Paper", "1994", "Comedy Drama", 2.99, "VHS");
VALUES ("The Pelican Brief", "1993", "Crime Drama Mystery", 2.99, "VHS");
VALUES ("The Piano", "1993", "Drama Music Romance", 2.99, "VHS");
VALUES ("The Princess Bride", "1987", "Adventure Family Fantasy", 2.99, "VHS");
VALUES ("The Rocky Horror Picture Show", "1975", "Comedy Musical", 2.99, "VHS");
VALUES ("The Shawshank Redemption", "1994", "Drama", 2.99, "VHS");
VALUES ("The Shining", "1980", "Drama Horror", 2.99, "VHS");
VALUES ("The Silence of the Lambs", "1991", "Crime Drama Thriller", 2.99, "VHS");
VALUES ("The Sound of Music", "1965", "Biography Drama Family", 2.99, "VHS");
VALUES ("The Sting", "1973", "Comedy Crime Drama", 2.99, "VHS");
VALUES ("The Sting", "1973", "Comedy Crime Drama", 2.99, "VHS");
VALUES ("The Swan Princess", "1994", "Animation Comedy Family", 2.99, "VHS");
VALUES ("The Ten Commandments", "1956", "Adventure Drama Fantasy", 2.99, "VHS");
VALUES ("The Terminator", "1984", "Action Sci-Fi", 2.99, "VHS");
VALUES ("The Texas Chainsaw Massacre", "1974", "Horror", 2.99, "VHS");
VALUES ("The Thing", "1982", "Horror Mystery Sci-Fi", 2.99, "VHS");
VALUES ("The Towering Inferno", "1974", "Action Drama Thriller", 2.99, "VHS");
VALUES ("The Toxic Avenger", "1984", "Action Comedy Horro", 2.99, "VHS");
VALUES ("The Transformers The Movie", "1986", "Animation Action Adventure", 2.99, "VHS");
VALUES ("The Untouchables", "1987", "Crime Drama Thriller", 2.99, "VHS");
VALUES ("The Warriors", "1979", "Action Crime Thriller", 2.99, "VHS");
VALUES ("The Wicker Man", "1973", "Horror, Mystery, Thriller", 2.99, "VHS");
VALUES ("Thelma and Louise", "1991", "Adventure Crime Drama", 2.99, "VHS");
VALUES ("They Live", "1988", "Action Horror Sci-Fi", 2.99, "VHS");
VALUES ("This is Spinal Tap", "1984", "Comedy Music", 2.99, "VHS");
VALUES ("Thumbelina", "1994", "Animatiioin Family Fantasy", 2.99, "VHS");
VALUES ("To Live and Die in L.A.", "1985", "Action Crime Drama", 2.99, "VHS");
VALUES ("Tombstone", "1993", "Action Biography Drama", 2.99, "VHS");
VALUES ("Tootsie", "1982", "Comedy Drama Romance", 2.99, "VHS");
VALUES ("Top Gun", "1986", "Action Drama", 2.99, "VHS");
VALUES ("Total Recall", "1990", "Action Sci-Fi Thriller", 2.99, "VHS");
VALUES ("Toy Story", "1995", "Animation Adventure Comedy", 2.99, "VHS");
VALUES ("Trading Places", "1983", "Comedy", 2.99, "VHS");
VALUES ("Tron", "1982", "Action Adventure Sci-Fi", 2.99, "VHS");
VALUES ("True Lies", "1994", "Crime Drama Romance", 2.99, "VHS");
VALUES ("True Romance", "1993", "Mystery Sci-Fi Thriller", 2.99, "VHS");
VALUES ("Twelve Monkeys", "1995", "Mystery Sci-Fi Thriller", 2.99, "VHS");
VALUES ("Twin Peaks: Fire Walk with Me", "1992", "Drama Horror Mystery", 2.99, "VHS");
VALUES ("Two-Lane Blacktop", "1971", "Drama", 2.99, "VHS");
VALUES ("UHF", "1989", "Comedy Drama", 2.99, "VHS");
VALUES ("Under Siege", "1992", "Action Thriller", 2.99, "VHS");
VALUES ("Wall Street", "1987", "Crime Drama", 2.99, "VHS");
VALUES ("WarGames", "1983", "Sci-Fi Thriller", 2.99, "VHS");
VALUES ("Watership Down", "1978", "Animation Adventure Drama", 2.99, "VHS");
VALUES ("Wayne's World", "1992", "Comedy Music", 2.99, "VHS");
VALUES ("Weird Science", "1985", "Comedy Romance Sci-Fi", 2.99, "VHS");
VALUES ("West Side Story", "1961", "Crime Drama Musical", 2.99, "VHS");
VALUES ("What About Bob", "1991", "Comedy", 2.99, "VHS");
VALUES ("What's Eating Gilbert Grape", "1993", "Drama", 2.99, "VHS");
VALUES ("When Harry Met Sally", "1989", "Comedy Drama Romance", 2.99, "VHS");
VALUES ("White Christmas", "1954", "Comedy Musical Romance", 2.99, "VHS");
VALUES ("White Men Can't Jump", "1992", "Comedy Drama Sport", 2.99, "VHS");
VALUES ("Who Framed Rodger Rabbit", "1988", "Animation Adventure Comedy", 2.99, "VHS");
VALUES ("Who's Afraid of Virginia Woolf?", "1966", "Drama", 2.99, "VHS");
VALUES ("Willow", "1988", "Action Adventure Drama", 2.99, "VHS");
VALUES ("Willy Wonka and the Chocolate Factory", "1971", "Family Fantasy Musical", 2.99, "VHS");
VALUES ("Working Girl", "1988", "Comedy Drama Romance", 2.99, "VHS");
VALUES ("Young Frankenstein", "1974", "Comedy", 2.99, "VHS");

SELECT * FROM films;